[package]
name = "rust_shell_util_v2"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
clap = { version = "4.0", features = ["derive"] } # ใช้ features = ["derive"]
serde = { version = "1.0", features = ["derive"] } # ใช้ features = ["derive"]
toml = "0.8"